version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=meeting_user
      - POSTGRES_PASSWORD=meeting_password
      - POSTGRES_DB=meeting_summarizer
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=meeting_user
      - POSTGRES_PASSWORD=meeting_password
      - POSTGRES_DB=meeting_summarizer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
